name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install node
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: 'npm' #cache the node modules to improve performance
                        
        - name: Install dependencies
          run: npm ci # install packages in package-lock

        - name: Run typescript
          run: npm i -g typescript && tsc

        - name: Run eslint
          run: npm run lint

    cypress-run:
      runs-on: ubuntu-latest
      needs: lint  #lint need to completely finished with success before run this
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        NEXT_PUBLI_API_URL: http://localhost:3000

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install node
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: 'npm' #cache the node modules to improve performance
                        
        - name: Install dependencies
          run:  npm ci

        - name: Build app
          uses: npm run build

        - name: Run Cypress Tests
          uses: cypress-io/github-action@v6
          with: 
                build: npm run build
                start: npm start
                wait-on: http://localhost
                browser: chrome
                config-file: #setup cypress
                record: false
                                
        - name: Uploda screenshots on failure
          uses: actions/upload-artifact@v4
          if: failure()
          with:
                name: cypress-screeshots
                path: cypress/screenshots
                if-no-files-found: ignore                          


                        